# Site settings
title: Zachary Blank's Website
email: blank72594@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first website, building it for ByteAcademy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zblank
github_username:  zblank

# Build settings
markdown: kramdown
